services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app
    container_name: golang-app
    restart: always
    ports:
      - "127.0.0.1:7373:7373"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - golang-network
  db:
    image: postgres
    container_name: golang-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "SuperPassword123"
      POSTGRES_DB: "api_store"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - golang-network

volumes:
  postgres-data:
networks:
  golang-network:
    driver: bridge
